// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChargeInfoBuf.proto

package com.pile.netty.message;

public final class ChargeInfoBufOuterClass {
  private ChargeInfoBufOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChargeInfoBufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.pile.model.ChargeInfoBuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *会员编号
     * </pre>
     *
     * <code>int32 memberId = 1;</code>
     */
    int getMemberId();

    /**
     * <pre>
     *充电桩桩体号
     * </pre>
     *
     * <code>string pileCode = 2;</code>
     */
    java.lang.String getPileCode();
    /**
     * <pre>
     *充电桩桩体号
     * </pre>
     *
     * <code>string pileCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getPileCodeBytes();

    /**
     * <pre>
     *充电桩编号
     * </pre>
     *
     * <code>int32 pileId = 3;</code>
     */
    int getPileId();

    /**
     * <pre>
     *充电枪编号
     * </pre>
     *
     * <code>int32 gunId = 4;</code>
     */
    int getGunId();

    /**
     * <pre>
     *充电单流水号
     * </pre>
     *
     * <code>string orderSerialNumber = 5;</code>
     */
    java.lang.String getOrderSerialNumber();
    /**
     * <pre>
     *充电单流水号
     * </pre>
     *
     * <code>string orderSerialNumber = 5;</code>
     */
    com.google.protobuf.ByteString
        getOrderSerialNumberBytes();

    /**
     * <pre>
     *服务费
     * </pre>
     *
     * <code>int32 serviceMoney = 6;</code>
     */
    int getServiceMoney();

    /**
     * <pre>
     *充电金额
     * </pre>
     *
     * <code>int32 chargeMoney = 7;</code>
     */
    int getChargeMoney();

    /**
     * <pre>
     *充电电量
     * </pre>
     *
     * <code>double chargeAmount = 8;</code>
     */
    double getChargeAmount();

    /**
     * <pre>
     *结束原因
     * </pre>
     *
     * <code>int32 endCause = 9;</code>
     */
    int getEndCause();
  }
  /**
   * Protobuf type {@code com.pile.model.ChargeInfoBuf}
   */
  public  static final class ChargeInfoBuf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.pile.model.ChargeInfoBuf)
      ChargeInfoBufOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChargeInfoBuf.newBuilder() to construct.
    private ChargeInfoBuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChargeInfoBuf() {
      memberId_ = 0;
      pileCode_ = "";
      pileId_ = 0;
      gunId_ = 0;
      orderSerialNumber_ = "";
      serviceMoney_ = 0;
      chargeMoney_ = 0;
      chargeAmount_ = 0D;
      endCause_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChargeInfoBuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              memberId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              pileCode_ = s;
              break;
            }
            case 24: {

              pileId_ = input.readInt32();
              break;
            }
            case 32: {

              gunId_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              orderSerialNumber_ = s;
              break;
            }
            case 48: {

              serviceMoney_ = input.readInt32();
              break;
            }
            case 56: {

              chargeMoney_ = input.readInt32();
              break;
            }
            case 65: {

              chargeAmount_ = input.readDouble();
              break;
            }
            case 72: {

              endCause_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pile.netty.message.ChargeInfoBufOuterClass.internal_static_com_pile_model_ChargeInfoBuf_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pile.netty.message.ChargeInfoBufOuterClass.internal_static_com_pile_model_ChargeInfoBuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf.class, com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf.Builder.class);
    }

    public static final int MEMBERID_FIELD_NUMBER = 1;
    private int memberId_;
    /**
     * <pre>
     *会员编号
     * </pre>
     *
     * <code>int32 memberId = 1;</code>
     */
    public int getMemberId() {
      return memberId_;
    }

    public static final int PILECODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object pileCode_;
    /**
     * <pre>
     *充电桩桩体号
     * </pre>
     *
     * <code>string pileCode = 2;</code>
     */
    public java.lang.String getPileCode() {
      java.lang.Object ref = pileCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pileCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *充电桩桩体号
     * </pre>
     *
     * <code>string pileCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPileCodeBytes() {
      java.lang.Object ref = pileCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pileCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PILEID_FIELD_NUMBER = 3;
    private int pileId_;
    /**
     * <pre>
     *充电桩编号
     * </pre>
     *
     * <code>int32 pileId = 3;</code>
     */
    public int getPileId() {
      return pileId_;
    }

    public static final int GUNID_FIELD_NUMBER = 4;
    private int gunId_;
    /**
     * <pre>
     *充电枪编号
     * </pre>
     *
     * <code>int32 gunId = 4;</code>
     */
    public int getGunId() {
      return gunId_;
    }

    public static final int ORDERSERIALNUMBER_FIELD_NUMBER = 5;
    private volatile java.lang.Object orderSerialNumber_;
    /**
     * <pre>
     *充电单流水号
     * </pre>
     *
     * <code>string orderSerialNumber = 5;</code>
     */
    public java.lang.String getOrderSerialNumber() {
      java.lang.Object ref = orderSerialNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderSerialNumber_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *充电单流水号
     * </pre>
     *
     * <code>string orderSerialNumber = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOrderSerialNumberBytes() {
      java.lang.Object ref = orderSerialNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderSerialNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICEMONEY_FIELD_NUMBER = 6;
    private int serviceMoney_;
    /**
     * <pre>
     *服务费
     * </pre>
     *
     * <code>int32 serviceMoney = 6;</code>
     */
    public int getServiceMoney() {
      return serviceMoney_;
    }

    public static final int CHARGEMONEY_FIELD_NUMBER = 7;
    private int chargeMoney_;
    /**
     * <pre>
     *充电金额
     * </pre>
     *
     * <code>int32 chargeMoney = 7;</code>
     */
    public int getChargeMoney() {
      return chargeMoney_;
    }

    public static final int CHARGEAMOUNT_FIELD_NUMBER = 8;
    private double chargeAmount_;
    /**
     * <pre>
     *充电电量
     * </pre>
     *
     * <code>double chargeAmount = 8;</code>
     */
    public double getChargeAmount() {
      return chargeAmount_;
    }

    public static final int ENDCAUSE_FIELD_NUMBER = 9;
    private int endCause_;
    /**
     * <pre>
     *结束原因
     * </pre>
     *
     * <code>int32 endCause = 9;</code>
     */
    public int getEndCause() {
      return endCause_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (memberId_ != 0) {
        output.writeInt32(1, memberId_);
      }
      if (!getPileCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pileCode_);
      }
      if (pileId_ != 0) {
        output.writeInt32(3, pileId_);
      }
      if (gunId_ != 0) {
        output.writeInt32(4, gunId_);
      }
      if (!getOrderSerialNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, orderSerialNumber_);
      }
      if (serviceMoney_ != 0) {
        output.writeInt32(6, serviceMoney_);
      }
      if (chargeMoney_ != 0) {
        output.writeInt32(7, chargeMoney_);
      }
      if (chargeAmount_ != 0D) {
        output.writeDouble(8, chargeAmount_);
      }
      if (endCause_ != 0) {
        output.writeInt32(9, endCause_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (memberId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, memberId_);
      }
      if (!getPileCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pileCode_);
      }
      if (pileId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pileId_);
      }
      if (gunId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, gunId_);
      }
      if (!getOrderSerialNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, orderSerialNumber_);
      }
      if (serviceMoney_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, serviceMoney_);
      }
      if (chargeMoney_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, chargeMoney_);
      }
      if (chargeAmount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, chargeAmount_);
      }
      if (endCause_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, endCause_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf)) {
        return super.equals(obj);
      }
      com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf other = (com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf) obj;

      boolean result = true;
      result = result && (getMemberId()
          == other.getMemberId());
      result = result && getPileCode()
          .equals(other.getPileCode());
      result = result && (getPileId()
          == other.getPileId());
      result = result && (getGunId()
          == other.getGunId());
      result = result && getOrderSerialNumber()
          .equals(other.getOrderSerialNumber());
      result = result && (getServiceMoney()
          == other.getServiceMoney());
      result = result && (getChargeMoney()
          == other.getChargeMoney());
      result = result && (
          java.lang.Double.doubleToLongBits(getChargeAmount())
          == java.lang.Double.doubleToLongBits(
              other.getChargeAmount()));
      result = result && (getEndCause()
          == other.getEndCause());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEMBERID_FIELD_NUMBER;
      hash = (53 * hash) + getMemberId();
      hash = (37 * hash) + PILECODE_FIELD_NUMBER;
      hash = (53 * hash) + getPileCode().hashCode();
      hash = (37 * hash) + PILEID_FIELD_NUMBER;
      hash = (53 * hash) + getPileId();
      hash = (37 * hash) + GUNID_FIELD_NUMBER;
      hash = (53 * hash) + getGunId();
      hash = (37 * hash) + ORDERSERIALNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getOrderSerialNumber().hashCode();
      hash = (37 * hash) + SERVICEMONEY_FIELD_NUMBER;
      hash = (53 * hash) + getServiceMoney();
      hash = (37 * hash) + CHARGEMONEY_FIELD_NUMBER;
      hash = (53 * hash) + getChargeMoney();
      hash = (37 * hash) + CHARGEAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getChargeAmount()));
      hash = (37 * hash) + ENDCAUSE_FIELD_NUMBER;
      hash = (53 * hash) + getEndCause();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.pile.model.ChargeInfoBuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.pile.model.ChargeInfoBuf)
        com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pile.netty.message.ChargeInfoBufOuterClass.internal_static_com_pile_model_ChargeInfoBuf_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pile.netty.message.ChargeInfoBufOuterClass.internal_static_com_pile_model_ChargeInfoBuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf.class, com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf.Builder.class);
      }

      // Construct using com.pile.model.ChargeInfoBufOuterClass.ChargeInfoBuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        memberId_ = 0;

        pileCode_ = "";

        pileId_ = 0;

        gunId_ = 0;

        orderSerialNumber_ = "";

        serviceMoney_ = 0;

        chargeMoney_ = 0;

        chargeAmount_ = 0D;

        endCause_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pile.netty.message.ChargeInfoBufOuterClass.internal_static_com_pile_model_ChargeInfoBuf_descriptor;
      }

      @java.lang.Override
      public com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf getDefaultInstanceForType() {
        return com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf.getDefaultInstance();
      }

      @java.lang.Override
      public com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf build() {
        com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf buildPartial() {
        com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf result = new com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf(this);
        result.memberId_ = memberId_;
        result.pileCode_ = pileCode_;
        result.pileId_ = pileId_;
        result.gunId_ = gunId_;
        result.orderSerialNumber_ = orderSerialNumber_;
        result.serviceMoney_ = serviceMoney_;
        result.chargeMoney_ = chargeMoney_;
        result.chargeAmount_ = chargeAmount_;
        result.endCause_ = endCause_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf) {
          return mergeFrom((com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf other) {
        if (other == com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf.getDefaultInstance()) return this;
        if (other.getMemberId() != 0) {
          setMemberId(other.getMemberId());
        }
        if (!other.getPileCode().isEmpty()) {
          pileCode_ = other.pileCode_;
          onChanged();
        }
        if (other.getPileId() != 0) {
          setPileId(other.getPileId());
        }
        if (other.getGunId() != 0) {
          setGunId(other.getGunId());
        }
        if (!other.getOrderSerialNumber().isEmpty()) {
          orderSerialNumber_ = other.orderSerialNumber_;
          onChanged();
        }
        if (other.getServiceMoney() != 0) {
          setServiceMoney(other.getServiceMoney());
        }
        if (other.getChargeMoney() != 0) {
          setChargeMoney(other.getChargeMoney());
        }
        if (other.getChargeAmount() != 0D) {
          setChargeAmount(other.getChargeAmount());
        }
        if (other.getEndCause() != 0) {
          setEndCause(other.getEndCause());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int memberId_ ;
      /**
       * <pre>
       *会员编号
       * </pre>
       *
       * <code>int32 memberId = 1;</code>
       */
      public int getMemberId() {
        return memberId_;
      }
      /**
       * <pre>
       *会员编号
       * </pre>
       *
       * <code>int32 memberId = 1;</code>
       */
      public Builder setMemberId(int value) {
        
        memberId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *会员编号
       * </pre>
       *
       * <code>int32 memberId = 1;</code>
       */
      public Builder clearMemberId() {
        
        memberId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object pileCode_ = "";
      /**
       * <pre>
       *充电桩桩体号
       * </pre>
       *
       * <code>string pileCode = 2;</code>
       */
      public java.lang.String getPileCode() {
        java.lang.Object ref = pileCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pileCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *充电桩桩体号
       * </pre>
       *
       * <code>string pileCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPileCodeBytes() {
        java.lang.Object ref = pileCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pileCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *充电桩桩体号
       * </pre>
       *
       * <code>string pileCode = 2;</code>
       */
      public Builder setPileCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pileCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *充电桩桩体号
       * </pre>
       *
       * <code>string pileCode = 2;</code>
       */
      public Builder clearPileCode() {
        
        pileCode_ = getDefaultInstance().getPileCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *充电桩桩体号
       * </pre>
       *
       * <code>string pileCode = 2;</code>
       */
      public Builder setPileCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pileCode_ = value;
        onChanged();
        return this;
      }

      private int pileId_ ;
      /**
       * <pre>
       *充电桩编号
       * </pre>
       *
       * <code>int32 pileId = 3;</code>
       */
      public int getPileId() {
        return pileId_;
      }
      /**
       * <pre>
       *充电桩编号
       * </pre>
       *
       * <code>int32 pileId = 3;</code>
       */
      public Builder setPileId(int value) {
        
        pileId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *充电桩编号
       * </pre>
       *
       * <code>int32 pileId = 3;</code>
       */
      public Builder clearPileId() {
        
        pileId_ = 0;
        onChanged();
        return this;
      }

      private int gunId_ ;
      /**
       * <pre>
       *充电枪编号
       * </pre>
       *
       * <code>int32 gunId = 4;</code>
       */
      public int getGunId() {
        return gunId_;
      }
      /**
       * <pre>
       *充电枪编号
       * </pre>
       *
       * <code>int32 gunId = 4;</code>
       */
      public Builder setGunId(int value) {
        
        gunId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *充电枪编号
       * </pre>
       *
       * <code>int32 gunId = 4;</code>
       */
      public Builder clearGunId() {
        
        gunId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object orderSerialNumber_ = "";
      /**
       * <pre>
       *充电单流水号
       * </pre>
       *
       * <code>string orderSerialNumber = 5;</code>
       */
      public java.lang.String getOrderSerialNumber() {
        java.lang.Object ref = orderSerialNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderSerialNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *充电单流水号
       * </pre>
       *
       * <code>string orderSerialNumber = 5;</code>
       */
      public com.google.protobuf.ByteString
          getOrderSerialNumberBytes() {
        java.lang.Object ref = orderSerialNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderSerialNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *充电单流水号
       * </pre>
       *
       * <code>string orderSerialNumber = 5;</code>
       */
      public Builder setOrderSerialNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderSerialNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *充电单流水号
       * </pre>
       *
       * <code>string orderSerialNumber = 5;</code>
       */
      public Builder clearOrderSerialNumber() {
        
        orderSerialNumber_ = getDefaultInstance().getOrderSerialNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *充电单流水号
       * </pre>
       *
       * <code>string orderSerialNumber = 5;</code>
       */
      public Builder setOrderSerialNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderSerialNumber_ = value;
        onChanged();
        return this;
      }

      private int serviceMoney_ ;
      /**
       * <pre>
       *服务费
       * </pre>
       *
       * <code>int32 serviceMoney = 6;</code>
       */
      public int getServiceMoney() {
        return serviceMoney_;
      }
      /**
       * <pre>
       *服务费
       * </pre>
       *
       * <code>int32 serviceMoney = 6;</code>
       */
      public Builder setServiceMoney(int value) {
        
        serviceMoney_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务费
       * </pre>
       *
       * <code>int32 serviceMoney = 6;</code>
       */
      public Builder clearServiceMoney() {
        
        serviceMoney_ = 0;
        onChanged();
        return this;
      }

      private int chargeMoney_ ;
      /**
       * <pre>
       *充电金额
       * </pre>
       *
       * <code>int32 chargeMoney = 7;</code>
       */
      public int getChargeMoney() {
        return chargeMoney_;
      }
      /**
       * <pre>
       *充电金额
       * </pre>
       *
       * <code>int32 chargeMoney = 7;</code>
       */
      public Builder setChargeMoney(int value) {
        
        chargeMoney_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *充电金额
       * </pre>
       *
       * <code>int32 chargeMoney = 7;</code>
       */
      public Builder clearChargeMoney() {
        
        chargeMoney_ = 0;
        onChanged();
        return this;
      }

      private double chargeAmount_ ;
      /**
       * <pre>
       *充电电量
       * </pre>
       *
       * <code>double chargeAmount = 8;</code>
       */
      public double getChargeAmount() {
        return chargeAmount_;
      }
      /**
       * <pre>
       *充电电量
       * </pre>
       *
       * <code>double chargeAmount = 8;</code>
       */
      public Builder setChargeAmount(double value) {
        
        chargeAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *充电电量
       * </pre>
       *
       * <code>double chargeAmount = 8;</code>
       */
      public Builder clearChargeAmount() {
        
        chargeAmount_ = 0D;
        onChanged();
        return this;
      }

      private int endCause_ ;
      /**
       * <pre>
       *结束原因
       * </pre>
       *
       * <code>int32 endCause = 9;</code>
       */
      public int getEndCause() {
        return endCause_;
      }
      /**
       * <pre>
       *结束原因
       * </pre>
       *
       * <code>int32 endCause = 9;</code>
       */
      public Builder setEndCause(int value) {
        
        endCause_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *结束原因
       * </pre>
       *
       * <code>int32 endCause = 9;</code>
       */
      public Builder clearEndCause() {
        
        endCause_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.pile.model.ChargeInfoBuf)
    }

    // @@protoc_insertion_point(class_scope:com.pile.model.ChargeInfoBuf)
    private static final com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf();
    }

    public static com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChargeInfoBuf>
        PARSER = new com.google.protobuf.AbstractParser<ChargeInfoBuf>() {
      @java.lang.Override
      public ChargeInfoBuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChargeInfoBuf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChargeInfoBuf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChargeInfoBuf> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.pile.netty.message.ChargeInfoBufOuterClass.ChargeInfoBuf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pile_model_ChargeInfoBuf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pile_model_ChargeInfoBuf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ChargeInfoBuf.proto\022\016com.pile.model\"\300\001" +
      "\n\rChargeInfoBuf\022\020\n\010memberId\030\001 \001(\005\022\020\n\010pil" +
      "eCode\030\002 \001(\t\022\016\n\006pileId\030\003 \001(\005\022\r\n\005gunId\030\004 \001" +
      "(\005\022\031\n\021orderSerialNumber\030\005 \001(\t\022\024\n\014service" +
      "Money\030\006 \001(\005\022\023\n\013chargeMoney\030\007 \001(\005\022\024\n\014char" +
      "geAmount\030\010 \001(\001\022\020\n\010endCause\030\t \001(\005B\020\n\016com." +
      "pile.modelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_pile_model_ChargeInfoBuf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_pile_model_ChargeInfoBuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pile_model_ChargeInfoBuf_descriptor,
        new java.lang.String[] { "MemberId", "PileCode", "PileId", "GunId", "OrderSerialNumber", "ServiceMoney", "ChargeMoney", "ChargeAmount", "EndCause", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
