#默认为443，可以修改为自己需要的端口
server:
  port: 8080
  servlet:
    context-path: /NBWaterMeterCollection
  tomcat: 
    uri-encoding: UTF-8
  
logging:
  level: 
    learning: debug

# REDIS (RedisProperties)
spring:
  resources: 
     static-locations: ["/templates/","/static/"]
  http: 
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    # Redis数据库索引（默认为0）
    database: 0  
    # Redis服务器地址
    host: 192.168.19.8
    # Redis服务器连接端口
    port: 6379  
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 20 
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        # 连接池中的最大空闲连接
        max-idle: 10  
        # 连接池中的最小空闲连接
        min-idle: 5 
      # 连接超时时间（毫秒）
    timeout: 5000
    
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    platform: mysql
    url: jdbc:sqlserver://192.168.19.9:1433;Databasename=ydpara
    username: sa
    password: keyd*%@#1095
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
  mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
       