#默认为443，可以修改为自己需要的端口
server:
  port: 8080
  servlet:
    context-path: /kecharge
  
logging:
  level: 
    learning: debug

# REDIS (RedisProperties)
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0  
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379  
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 20 
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        # 连接池中的最大空闲连接
        max-idle: 10  
        # 连接池中的最小空闲连接
        min-idle: 5 
      # 连接超时时间（毫秒）
    timeout: 5000

interceptor: 
  urls: /test,/test1
  
